/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.travels.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Stage service. Represents a row in the &quot;LiferayTravels_Stage&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.travels.model.impl.StageModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.travels.model.impl.StageImpl</code>.
 * </p>
 *
 * @author Javier de Arcos
 * @see Stage
 * @generated
 */
@ProviderType
public interface StageModel extends BaseModel<Stage> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a stage model instance should use the {@link Stage} interface instead.
	 */

	/**
	 * Returns the primary key of this stage.
	 *
	 * @return the primary key of this stage
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this stage.
	 *
	 * @param primaryKey the primary key of this stage
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this stage.
	 *
	 * @return the uuid of this stage
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this stage.
	 *
	 * @param uuid the uuid of this stage
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the stage ID of this stage.
	 *
	 * @return the stage ID of this stage
	 */
	public long getStageId();

	/**
	 * Sets the stage ID of this stage.
	 *
	 * @param stageId the stage ID of this stage
	 */
	public void setStageId(long stageId);

	/**
	 * Returns the name of this stage.
	 *
	 * @return the name of this stage
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this stage.
	 *
	 * @param name the name of this stage
	 */
	public void setName(String name);

	/**
	 * Returns the description of this stage.
	 *
	 * @return the description of this stage
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this stage.
	 *
	 * @param description the description of this stage
	 */
	public void setDescription(String description);

	/**
	 * Returns the place of this stage.
	 *
	 * @return the place of this stage
	 */
	@AutoEscape
	public String getPlace();

	/**
	 * Sets the place of this stage.
	 *
	 * @param place the place of this stage
	 */
	public void setPlace(String place);

	/**
	 * Returns the image of this stage.
	 *
	 * @return the image of this stage
	 */
	@AutoEscape
	public String getImage();

	/**
	 * Sets the image of this stage.
	 *
	 * @param image the image of this stage
	 */
	public void setImage(String image);

	/**
	 * Returns the trip ID of this stage.
	 *
	 * @return the trip ID of this stage
	 */
	public long getTripId();

	/**
	 * Sets the trip ID of this stage.
	 *
	 * @param tripId the trip ID of this stage
	 */
	public void setTripId(long tripId);

}